### PR TITLE
fix: done layout with Flexbox

### PR DESCRIPTION
**Pull request by ShreyashMahajan**
First, the layout was not made with the help of flexbox, So now the layout has been updated with the help of flex.
please review the code and help for improvement

### CODE REVIEW

**Review by sks-21 — APPROVED** [review]
The code looks nice. Good work

**Review by SaurabhChawda — COMMENTED** [review]
You can Merge it.

**Comment by ShreyashMahajan** [comment]
> The code looks nice. Good work
thank you, I will do that

**Comment by ShreyashMahajan** [comment]
> You can Merge it.
thank you

**Review by SaurabhChawda — APPROVED** [review]

**Pull request merged**
